import React, { Component } from 'react';
import { Form } from 'antd';
import classNames from 'classnames/bind';
import styles from './style.mod.less';
import axios from 'axios';
import Base from 'app/util/base';

const cx = classNames.bind(styles);

class Step extends Component {
  constructor(props) {
    super(props);
    this.state = {
      randomCode: '//vip.woqu.com/code?key=image_auth_code',
      email: null,
      name: null,
      disable: true,
    };
  }

  componentWillMount() {
    const { shopCode } = this.props;
    shopCode && axios({
      url: `${Base.api}/merchant/merchant-detail-${shopCode}`,
      headers:{'Content-Type': 'application/json'}
    }).then(res => {
      const data = res.data;
      if ( data.result ) {
        this.setState({
          name: data.returnObject.shopNameEn,
          email: data.returnObject.contactEmail,
          disable: false
        });
      }
    });
  }

  render() {
    return(
      <div>
        <div className={cx('resform')}>
          <h2>MERCHANT AGREEMENT</h2>
          <p>This Merchant Agreement (the “Agreement”) is made and entered into as of the date you click “I Accept” below (the “Effective Date”), by and between i++ Travel Group, a Cayman Islands Corporation with its principal place of business at 2890 Zanker Rd, #203, San Jose, 95134, and its affiliates (collectively, “i++ Travel Group”), and <span style={{padding:'0 20px',borderBottom:'1px solid #333'}}>{this.state.name}</span>(“Merchant”).</p>
          <p><strong>A.</strong>&nbsp;&nbsp;i++ Travel Group’s WeChat mini mobile application (the “App”) enables users of the WeChat application (“Users”) to access information about local places of interest such as, restaurants, bike rentals, sightseeing attractions, tours, excursions, hotels, etc. (“Businesses”).  Via the App, i++ Travel Group makes available such information, including, but not limited to, menus, rental agreement terms, hotel policies, rates and charges, booking fees, etc. provided to it by the respective Businesses (the “Business Details”) in various languages. i++ Travel Group’s website, the App and translation services are collectively referred to as the “Services”. The Users can access these translated Business Details in the App, by scanning a unique code provided by i++ Travel Group to the applicable Business (the “QR Code”), via the Services.</p>
          <p><strong>B.</strong>&nbsp;&nbsp;Merchant operates one such Business, and wants to include its Business and Business Details in the App. NOW, THEREFORE, in consideration of the foregoing and other good and valuable consideration, the receipt and sufficiency of which is hereby acknowledged, the parties hereby agree as follows:</p>
          <h3>1. MERCHANT’S OBLIGATIONS</h3>
          <p><strong>1.1</strong>&nbsp;&nbsp;Provision of Business Details. On or before the Effective Date, Merchant will provide i++ Travel Group its latest and most up-to-date Business Details in a manner and format that is acceptable to i++ Travel Group. Merchant may choose to provide to i++ Travel Group the Business Details already translated in the languages of its choice, or it may request i++ Travel Group to translate its Business Details into the language(s) that i++ Travel Group offers the translation in, for a fee as described on the Payments page (under construction). i++ Travel Group will make such translated Business Details available to Users who scan the Merchant’s QR Code, via its App. Merchant agrees to update its Business Details and provide such updates to i++ Travel Group at least 30 days before such updated Business Details go into effect. In the event Merchant fails to update i++ Travel Group with its latest Business Details on time, it will be obliged to honor the Business Details that it had last provided to i++ Travel Group, and which are available via the App.</p>
          <p><strong>1.2</strong>&nbsp;&nbsp;License to Business Details.  Merchant grants to i++ Travel Group a non-exclusive, worldwide, royalty-free license, during the Term, with the right to sublicense through multiple tiers, to use, copy, reproduce, modify (for formatting purposes only), create derivative works based upon (for translation purposes only), distribute copies of, publicly display, publicly perform, and use, the Business Details, for inclusion in the App.</p>
          <p><strong>1.3</strong>&nbsp;&nbsp;Merchant Trademark License. Merchant grants to i++ Travel Group a non-exclusive, non-transferable, royalty-free license, during the Term, to use Merchant’s trademarks, service marks, and logos identifying Merchant (the “Merchant Marks”) provided by Merchant to i++ Travel Group for the purposes of inclusion of Merchant in the App and using them in i++ Travel Group’s marketing materials. All goodwill created by or that results from the use of such marks inures solely to the benefit of Merchant.</p>
          <p><strong>1.4</strong>&nbsp;&nbsp;QR Code.  During the Term, Merchant agrees to display the QR Code at a conspicuous place (e.g. on the Menu of a restaurant), or present it to the Users (e.g. by a waiter presenting it). In addition, Merchant will use reasonable efforts to display a sign of the QR Code provided by i++ Travel Group in a prominent place at its place of business, so that Users can easily spot it.</p>
          <p><strong>1.5</strong>&nbsp;&nbsp;Merchant’s Quality of Business.  Merchant agrees to (i) maintain its facilities, equipment, and other materials used in its Business in accordance with the highest industry standards for the health, safety and security of Users, and (ii) comply with all relevant laws and regulations, including, maintaining any requisite licenses, applicable to it and its Business.</p>
          <p><strong>1.6</strong>&nbsp;&nbsp;Offensive or Disparaging Content.  Merchant agrees that the Business Details provided to i++ Travel Group will not contain any offensive content nor will it portray i++ Travel Group in a disparaging way. Should any offensive or disparaging content be found in the Business Details, Merchant will remove such content immediately and i++ Travel Group will have the right to terminate this Agreement immediately.</p>
          <h3>2. i++ TRAVEL GROUP’S OBLIGATIONS</h3>
          <p><strong>2.1</strong>&nbsp;&nbsp;Translation Services; QR Code.  Merchant may provide the translated Business Details to i++ Travel Group, which i++ Travel Group will make available to the Users who scan the Merchant’s QR Code via its App. Alternatively, Merchant may request i++ Travel Group to translate its Business Details for a fee as provided on the Payments Page (under construction)., and i++ Travel Group will translate the Business Details  into the language or languages that it offers its Services for, via the functionality of the App, and create a QR Code via which such translated Business Details will be accessible by the Users.   Such QR Code will be available to Merchant within a reasonable time of Merchant’s provision of the Business Details to i++ Travel Group.   Merchant understands and agrees that i++ Travel Group uses diligent efforts to translate the Business Details however, i++ Travel Group disclaims all liability or damages that may be caused or awarded in connection with such translation.</p>
          <p><strong>2.2</strong>&nbsp;&nbsp;Trademark License. i++ Travel Group grants to Merchant a non-exclusive, non-transferable, royalty-free license, during the Term, to use i++ Travel Group’s trademarks, service marks, and logos identifying i++ Travel Group (the “i++ Travel Group Marks”) provided by i++ Travel Group to Merchant to promote i++ Travel Group at Merchant’s place of business and on Merchant’s website and to display the i++ Travel Group Marks with the QR Code. All goodwill created by or that results from the use of such marks inures solely to the benefit of i++ Travel Group.</p>
          <h3>3. FINANCIAL TERMS</h3>
          <p><strong>3.1</strong>&nbsp;&nbsp;Referral Fee.  i++ Travel Group may from time to time, offer a referral program under which the Merchant will have the opportunity to earn a referral fee for referring its customers to i++ Travel Group (“Merchant Referral Program”). When i++ Travel Group offers such Merchant Referral Program to Merchant,  i++ Travel Group will pay Merchant a referral fee for each Referred Customer calculated in accordance with the terms set forth on its Merchant Referral Program page (under construction) (the “Referral Fee”).  A “Referred Customer” means a User who satisfies all of the following conditions: (i) is a registered User of the App (ii) has made a reservation or booking for at least one of the paid activities offered on the Services by accessing the App via Merchant’s QR Code (“Reserved Activity”);  (iii) has paid i++ Travel Group the full amount for that Reserved Activity; and (iv) has successfully completed or participated in the applicable Reserved Activity which was booked via the QR Code. If a User views an activity available to them via the App by scanning the Merchant’s QR Code, but does not book the activity or pay for them using that QR Code, then Merchant will not be eligible for the Referral Fee, even if such User later books that activity either independently or by scanning a different merchant’s QR Code.</p>
          <p><strong>3.2</strong>&nbsp;&nbsp;Payment Terms.  A Referral Fee is due and payable by i++ Travel Group to Merchant on a monthly basis, at the end of each month in which the Referral Fee accrues, provided the Merchant has accrued at least $100 towards Referral Fee . All payments are payable in U.S. dollars. i++ Travel Group reserves the right to change this payment policy and the fund transfer method, upon prior written notice to Merchant.</p>
          <p><strong>3.3</strong>&nbsp;&nbsp;Program Fee.  The program fee consists of a one-time sign-up fee, and a monthly service fee.  Merchant may choose to make the payment to Lulutrip on a monthly basis or on an annual basis. The amount due and the accepted payment methods are specified in Merchant’s account at <a href="https://www.ipptraveltech.com">https://www.ipptraveltech.com</a>.  At its sole discretion, Lulutrip may waive or discount the Program Fee.  Lulutrip reserves the right to change this payment policy and the fund transfer method, upon prior written notice to Merchant.</p>
          <h3>4.	OWNERSHIP</h3>
          <p><strong>4.1</strong>&nbsp;&nbsp;i++ Travel Group Materials. i++ Travel Group and its licensors exclusively own all right, title and interest in and to the Services and i++ Travel Group Marks (collectively, “i++ Travel Group Materials”) including all associated intellectual property rights. All rights to the i++ Travel Group Materials except those expressly granted to Merchant herein, are reserved to i++ Travel Group and its licensors.</p>
          <p><strong>4.2</strong>&nbsp;&nbsp;Merchant Materials.  Merchant owns all right, title and interest in its Business Details and Merchant Marks (collectively, “Merchant Materials”) including all associated intellectual property rights. All rights to the Merchant Materials except those expressly granted to i++ Travel Group herein, are reserved to Merchant and its licensors.</p>
          <h3>5.	WARRANTY AND LIMITATION OF LIABILITY</h3>
          <p><strong>5.1</strong>&nbsp;&nbsp;Mutual Representations and Warranties.  Each party represents and warrants that (a) it has the power and authority to enter into this Agreement, (b) it will comply with all applicable laws in relation to its business and its rights and obligations hereunder, and (c) its performance of obligations under this Agreement will not breach any obligation of confidentiality to a third party.</p>
          <p><strong>5.2</strong>&nbsp;&nbsp;Representations and Warranties by Merchant.  Merchant represents and warrants that: (i) Merchant owns all Merchant Materials or has all rights that are necessary to grant to i++ Travel Group the license rights granted under this Agreement, and none of the Merchant Materials will infringe, misappropriate or violate a third party’s intellectual property rights; (ii) the Business Details are accurate and up to date; and (iii) Merchant has obtained all the necessary licenses, authorizations, and approvals to run its Business as currently conducted.</p>
          <p><strong>5.3</strong>&nbsp;&nbsp;Warranty Disclaimer.  EXCEPT FOR THE FOREGOING, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, EACH PARTY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.</p>
          <p><strong>5.4</strong>&nbsp;&nbsp;Limitation of Liability.  EXCEPT FOR LIABILITY ARISING FROM THE INDEMNIFICATION OBLIGATIONS UNDER THIS AGREEMENT, IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THIS AGREEMENT, EVEN IF SUCH PARTY HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES. EXCEPT FOR LIABILITY ARISING FROM INDEMNITY OBLIGATIONS, IN NO EVENT WILL A PARTY’S LIABILITY TO THE OTHER PARTY UNDER THIS AGREEMENT FROM ALL CAUSES OF ACTION AND UNDER ALL THEORIES OF LIABILITY, EXCEED THE AMOUNT OF THE REFERRAL FEE PAID OR PAYABLE TO MERCHANT UNDER THE AGREEMENT IN THE TWELVE MONTHS PRECEDING THE CLAIM.</p>
          <h3>6. INDEMNITY</h3>
          <p><strong>6.1</strong>&nbsp;&nbsp;Mutual Indemnity. Each party will defend, indemnify and hold the other party harmless from and against all claims, damages, liabilities, losses, expenses and costs (including reasonable fees and expenses of attorneys and other professionals) (collectively, “Claims”) arising out of or resulting from any third party claim based on or resulting from a breach of the indemnifying party’s representations and warranties made under this Agreement. The indemnifying party is obligated to indemnify the indemnified party provided that the indemnified party: (a) promptly notifies indemnifying party in writing of any such claim; (b) grants indemnifying party sole control of the defense and settlement of the claim; and (c) provides indemnifying party, at indemnifying party’s expense, with all assistance, information and authority reasonably required for the defense and settlement of the claim.</p>
          <p><strong>6.2</strong>&nbsp;&nbsp;Indemnification by Merchant.  Merchant agrees to indemnify, defend, and hold harmless i++ Travel Group and its officers, directors, agents, and employees (each, an “Indemnitee“) from and against any and all liabilities, damages, losses, expenses, claims, demands, suits, fines, or judgments (each, a “Merchant Indemnified Claim,” and collectively, the “Merchant Indemnified Claims“), including reasonable attorneys’ fees, costs, and expenses incidental thereto, which may be suffered by, incurred by, accrued against, charged to, or recoverable from any Indemnitee, by reason of any Merchant Indemnified Claim arising out of or relating to any act, error or omission, negligence, or misconduct of Merchant, its officers, directors, agents, employees, and subcontractors, during the performance of this Agreement, including, without limitation, Merchant Indemnified Claims arising out of or relating to (a) bodily injury (including death) or damage to tangible personal or real property; (b) any payment required to be paid to subcontractors, if any, of Merchant;  or (c) infringing or misappropriating any United States or foreign patent, copyright, trade secret, trademark, or other proprietary right; provided, however, that the foregoing indemnity shall not apply to the extent that the applicable Merchant Indemnified Claim resulted from the acts or omissions of an Indemnitee. Upon receipt by Indemnitee of a threat, notice, or filing of any Merchant Indemnified Claim against an Indemnitee, Indemnitee will follow the indemnification procedures as described in Section 6.1.</p>
          <h3>7. 1.	TERM AND TERMINATION</h3>
          <p><strong>7.1</strong>&nbsp;&nbsp;Term.  Subject to earlier termination by either party in accordance with the terms of this Agreement, the Agreement will commence on the Effective Date and continue for a period of one year (the “Initial Term”) after which the Agreement will automatically renew for one year terms unless one party notifies the other party in writing, of its intention not to renew at least thirty (30) days prior to the expiration of the then‑current term (“Renewal Term”). Initial Term and Renewal Terms are collectively referred to as “Term”.</p>
          <p><strong>7.2</strong>&nbsp;&nbsp;Termination for Cause. Either party will have the right to terminate this Agreement if: (i) the other party breaches any material term or condition of this Agreement and fails to cure such breach within fifteen (15) days after receipt of written notice thereof.</p>
          <p><strong>7.3</strong>&nbsp;&nbsp;Effect of Termination. Upon the expiration or any termination of this Agreement: (i) Merchant will promptly stop using the QR Code, and (ii) the licenses granted by the parties will automatically terminate.  Notwithstanding the above, Merchant will honor all reservations and bookings made by the Users via the QR Code, before the termination or expiration of the Agreement.</p>
          <p><strong>7.4</strong>&nbsp;&nbsp;1.1	Survival. The rights and obligations of the parties under Sections 4, 5, 6, 7.3, 7.4 and 8 will survive the expiration or termination of this Agreement.</p>
          <h3>8. GENERAL</h3> 
          <p><strong>8.1</strong>&nbsp;&nbsp;This Agreement will be governed by California Law, without regard to or application of conflict of laws rules or principles. Merchant may not assign or transfer this Agreement, or any rights granted hereunder, in whole or in part, without i++ Travel Group’s prior written consent. i++ Travel Group may freely assign or transfer this Agreement in whole or in part. Subject to the foregoing, the Agreement inures to the benefit of the permitted successors and assigns. Except as expressly set forth in this Agreement, the exercise by either party of any of its remedies under this Agreement will be without prejudice to its other remedies under this Agreement or otherwise. All notices required to be sent will be in writing and sent to the [<span style={{padding:'0 20px',borderBottom:'1px solid #333'}}>{this.state.email}</span>]. Any material amendment of any provision of this Agreement will be effective only if accepted by authorized representatives of both parties; it being understood that acceptance of a modification by clicking “I Accept” will suffice. If any provision of this Agreement is held to be unenforceable or invalid, that provision will be enforced to the maximum extent possible, and the other provisions will remain in full force and effect. Nothing in this Agreement will be construed to create a partnership, joint venture or agency relationship between the parties. Neither party will be responsible for any failure or delay in its performance under this Agreement due to causes beyond its reasonable control, including, but not limited to, labor disputes, denial of service attacks, war, terrorism, riot, or acts of God. This Agreement is the complete and exclusive understanding and agreement between the parties regarding its subject matter, and supersedes all proposals, understandings or communications between the parties, oral or written, regarding its subject matter.</p>
          <p>IF YOU AGREE TO THE FOREGOING TERMS AND CONDITIONS, PLEASE CLICK THE “I ACCEPT” BUTTON BELOW.</p>
        </div>
      </div>
    )
  }
}

const StepC = Form.create()(Step);
export default StepC;
